# Site settings
title: Zoltan Kochan
email: zoltan.kochan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack web developer
baseurl: # the subpath of your site, e.g. /blog/
url: "https://www.kochan.io" # the base hostname & protocol for your site
twitter_username: "@ZoltanKochan"
github_username:  zkochan
github_repository: https://github.com/zkochan/zkochan.github.io

permalink: none

paginate: 5

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap