# Site settings
title: Zoltan Kochan
email: zoltan.kochan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack web developer
baseurl: / # the subpath of your site, e.g. /blog/
url: "http://www.kochan.io" # the base hostname & protocol for your site
twitter_username: "@ZoltanKochan"
github_username:  zkochan

paginate: 5

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
