# Site settings
title: Zoltan Kochan
email: zoltan.kochan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Zoltan Kochan. I am a full stack web developer. This is my
  blog about programming and technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kochan.io" # the base hostname & protocol for your site
twitter_username: ZoltanKochan
github_username:  zkochan

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
